export function Skills() {
  return (
    <>
      <img
        alt='React'
        src='https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB'
      />
      <img
        alt='Expo'
        src='https://img.shields.io/badge/Expo-1B1F23?style=for-the-badge&logo=expo&logoColor=white'
      />
      <img
        alt='Angular'
        src='https://img.shields.io/badge/Angular-DD0031?style=for-the-badge&logo=angular&logoColor=white'
      />
      <img
        alt='shadcn/ui'
        src='https://img.shields.io/badge/shadcn%2Fui-000000?style=for-the-badge&logo=shadcnui&logoColor=white'
      />
      <img
        alt='Tailwind CSS'
        src='https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=for-the-badge&logo=tailwind-css&logoColor=white'
      />
      <img
        alt='Node.js'
        src='https://img.shields.io/badge/Node%20js-339933?style=for-the-badge&logo=nodedotjs&logoColor=white'
      />
      <img
        alt='.NET'
        src='https://img.shields.io/badge/.NET-512BD4?style=for-the-badge&logo=dotnet&logoColor=white'
      />
      <img
        alt='Elastic'
        src='https://img.shields.io/badge/Elastic-005571?style=for-the-badge&logo=elastic&logoColor=white'
      />
      <img
        alt='GraphQL'
        src='https://img.shields.io/badge/GraphQl-E10098?style=for-the-badge&logo=graphql&logoColor=white'
      />
      <img
        alt='JWT'
        src='https://img.shields.io/badge/JWT-000000?style=for-the-badge&logo=JSON%20web%20tokens&logoColor=white'
      />
      <img
        alt='Prisma'
        src='https://img.shields.io/badge/Prisma-3982CE?style=for-the-badge&logo=Prisma&logoColor=white'
      />
      <img
        alt='PostgreSQL'
        src='https://img.shields.io/badge/PostgreSQL-316192?style=for-the-badge&logo=postgresql&logoColor=white'
      />
      <img
        alt='MongoDB'
        src='https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white'
      />
      <img
        alt='MSSQL'
        src='https://img.shields.io/badge/MSSQL-CC2927?style=for-the-badge&logo=databricks&logoColor=white'
      />
      <img
        alt='MySQL'
        src='https://img.shields.io/badge/MySQL-005C84?style=for-the-badge&logo=mysql&logoColor=white'
      />
      <img
        alt='Redis'
        src='https://img.shields.io/badge/redis-CC0000.svg?&style=for-the-badge&logo=redis&logoColor=white'
      />
      <img
        alt='Docker'
        src='https://img.shields.io/badge/Docker-2CA5E0?style=for-the-badge&logo=docker&logoColor=white'
      />
      <img
        alt='IIS'
        src='https://img.shields.io/badge/IIS-CC2927?style=for-the-badge&logo=databricks&logoColor=white'
      />
      <img
        alt='Nginx'
        src='https://img.shields.io/badge/Nginx-009639?style=for-the-badge&logo=nginx&logoColor=white'
      />
      <img
        alt='Google Cloud'
        src='https://img.shields.io/badge/Google_Cloud-4285F4?style=for-the-badge&logo=google-cloud&logoColor=white'
      />
      <img
        alt='Cloudflare'
        src='https://img.shields.io/badge/Cloudflare-000000?style=for-the-badge&logo=Cloudflare&logoColor=orange'
      />
    </>
  )
}
